fix(node): fix node values
3slab/helm-charts pull request #7
Opened 2020-10-20 15:21 UTC by angelfs

2020-10-20 17:13 UTC, jbouzekri requested changes

2020-10-20 17:13 UTC, jbouzekri commented on stable/node/templates/deployment.yaml
> +        {{ if .Values.command.enabled }}
Pourquoi ne pas rendre la commande paramétrable tout simplement ?

2020-10-21 07:45 UTC, angelfs commented on stable/node/templates/deployment.yaml
> +        {{ if .Values.command.enabled }}
Yes c'est pas faux, je corrige ;)

2020-10-21 08:14 UTC, jbouzekri approved these changes

2020-10-21 08:14 UTC, merged